sudo: required
language: python
services:
  - docker
install:
  - pip install ansible==2.3.2 molecule==1.25.0 docker git-semver
script:
  - chmod +x ./.travis/script.sh && bash ./.travis/script.sh
before_deploy:
  - chmod +x ./.travis/bdeploy.sh && bash ./.travis/bdeploy.sh
deploy:
  provider: script
  skip_cleanup: true
  script: git push https://${GH_TOKEN}:@${GIT_URL} --tags
  on:
    branch: master
#do not start when tag is added
branches:
  only:
    - master
tags:
  except:
    - /^\d+\.\d+\.\d+$/
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
after_success:
  - chmod +x ./.travis/after.sh && bash ./.travis/after.sh
after_failure:
  - chmod +x ./.travis/after.sh && bash ./.travis/after.sh