---
- name: Ensure dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ jenkins_dependencies }}"

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  when: ansible_os_family == 'RedHat'

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"
  when: ansible_os_family == 'RedHat'

- name: Install Jenkins from repository.
  package:
    name: jenkins
    state: "{{ 'latest' if jenkins_upgrade else 'installed' }}"
  notify:
  - groovy admin script
  - restart jenkins

- name: Modify variables in init file
  lineinfile:
    dest: "{{ jenkins_system_vars_file }}"
    insertafter: '^{{ jenkins_system_java_var }}='
    regexp: '^{{ jenkins_system_java_var }}=\"\${{ jenkins_system_java_var }} '
    line: '{{ jenkins_system_java_var }}="${{ jenkins_system_java_var }} -Djenkins.install.runSetupWizard=false"'
    state: present
  register: fresh_install
  notify: restart jenkins

- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- meta: flush_handlers
