---
# Jenkins doesn't allow updates via CLI, though that is required before plugins
# can be installed via CLI. See: https://gist.github.com/rowan-m/1026918
- name: Create Jenkins updates folder.
  file:
    path: "{{ jenkins_home }}/updates"
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory
  register: jenkins_plugins_folder_create

- name: Update Jenkins plugin data.
  get_url:
    url: "https://updates.jenkins-ci.org/update-center.json"
    dest: "{{ jenkins_home }}/updates/default.json"
    owner: jenkins
    group: jenkins
    mode: 0755

- name: install plugins
  jenkins_plugin:
    name: "{{ item }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
      url: http://localhost:8080
  with_items:
    - "git"
    - "git-client"
    - "blueocean-autofavorite"
    - "blueocean-commons"
    - "blueocean-config"
    - "blueocean-dashboard"
    - "blueocean-display-url"
    - "blueocean-events"
    - "blueocean-i18n"
    - "blueocean-jwt"
    - "blueocean-personalization"
    - "blueocean-pipeline-api-impl"
    - "blueocean-rest-impl"
    - "blueocean-rest"
    - "blueocean-web"
    - "blueocean"
    - "credentials"
    - "credentials-binding"
    - "dashboard-view"
    - "ssh-agent"
    - "ssh-credentials"
    - "ssh-slaves"
    - "greenballs"
    - "mattermost"
  notify: restart jenkins

- name: install docker
  jenkins_plugin:
    name: "{{ item }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
      url: http://localhost:8080
  with_items:
    - "docker-build-publish"
    - "docker-commons"
    - "docker-plugin"
    - "docker-workflow"
    - "sbt"
  when: jenkins_plugins_check_docker
  notify: restart jenkins

- name: install plugins gitlab
  jenkins_plugin:
    name: "{{ item }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
      url: http://localhost:8080
  with_items:
      - "gitlab-hook"
      - "gitlab-merge-request-jenkins"
      - "gitlab-oauth"
      - "gitlab-plugin"
  when: jenkins_plugins_check_gitlab
  notify: restart jenkins

- name: install plugins github
  jenkins_plugin:
    name: "{{ item }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
      url: http://localhost:8080
  with_items:
    - "github"
    - "github-api"
    - "github-branch-source"
  when: jenkins_plugins_check_github
  notify: restart jenkins

- name: install plugins additional
  jenkins_plugin:
    name: "{{ item }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
      url: http://localhost:8080
  with_items: "{{ additional_plugins | default([]) }}"
  when: jenkins_plugins_check_additional
  notify: restart jenkins
