---
- name: Ensure dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ jenkins_dependencies }}"

- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  when: ansible_os_family == 'RedHat'

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"
  when: ansible_os_family == 'RedHat'

- name: Install Jenkins from repository.
  package:
    name: jenkins
    state: installed
  notify: groovy admin script

- debug:
    msg: STEP AFTER JENKINS INSTALLATION

- name: Install additional groovy scripts
  jenkins_script:
      script: "templates/{{ item }}"
      user: "{{ jenkins_admin_username }}"
      password: "{{ jenkins_admin_password }}"
  with_items: "{{ jenkins_groovy_scripts }}"

- debug:
    msg: STEP AFTER PLUGINS INSTALLATION

- name: Modify variables in init file
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^{{ item.option }}='
    regexp: '^{{ item.option}}=\"\${{ item.option }} '
    line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
    state: present
  with_items:
      "{{ jenkins_init_changes }}"
  notify: restart jenkins

- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- meta: flush_handlers