---
- name: Ensure dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ jenkins_dependencies }}"

#DEBIAN/UBUNTU
- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

#REDHAT
- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  when: ansible_os_family == 'RedHat'

- name: Add Jenkins repo GPG key.
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"
  when: ansible_os_family == 'RedHat'

- name: Install Jenkins from repository.
  package:
    name: jenkins
    state: installed
  register: jenkins_fresh_install
