---
- name: Check if security script exist (it shouldn't)
  stat:
    path: /var/lib/jenkins/init.groovy.d/basic-security.groovy
  register: st
  failed_when: st.stat.exists == True

- name: Check if credentials script exist (it shouldn't)
  stat:
    path: /var/lib/jenkins/init.groovy.d/secret-text-credentials.groovy
  register: st
  failed_when: st.stat.exists == True

- name: Check if jenkins is running
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/"
    status_code: 403

- name: Check logging in with credentials
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes